import Link from "next/link";

import { site } from "@/lib/content";
import { cn } from "@/lib/utils";

/**
 * The brand mark: the supplied "KB" monogram with its leaf.
 *
 * Two things about how it is used here.
 *
 * The header lockup runs about 42px tall, and at that size the "ESTD 1870"
 * line in the full logo is roughly three pixels high — unreadable, and it
 * muddies the monogram. So the header and footer use the monogram-only
 * derivation (`logo-mark.svg`); the full lockup with the date is kept at
 * `public/brand/logo-full.svg` for placements with room for it.
 *
 * The monogram's K and swoosh are #207C38, which sits at roughly 1.5:1 against
 * the footer's #10261D and effectively vanishes. `tone="light"` swaps to the
 * reversed artwork, where those shapes are redrawn in the page surface colour
 * and only the leaf keeps its greens.
 *
 * Both files are generated by `npm run gen:logo` from the original in
 * `Images/`, so a logo revision is one command rather than a hand edit.
 */

/** Source artwork is 82 × 105 once the date line is removed. */
const MARK_RATIO = 82 / 105;

export function Mark({
  className,
  tone = "ink",
  height = 42,
}: {
  className?: string;
  tone?: "ink" | "light";
  height?: number;
}) {
  const src = "/brand/logo-custom.svg";
  // The new logo is 108.97 x 150 (roughly). Let's let the width be auto based on height.
  // We'll remove the explicit width so it scales naturally with the height.

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt=""
      aria-hidden="true"
      height={height}
      className={cn("block shrink-0 w-auto", className)}
      style={{ height }}
    />
  );
}

export function Wordmark({
  className,
  tone = "ink",
}: {
  className?: string;
  tone?: "ink" | "light";
}) {
  return (
    <Link
      href="/"
      className={cn("group inline-flex items-center gap-3", className)}
      aria-label={`${site.name} — home`}
    >
      <Mark tone={tone} />

      <span className="flex flex-col leading-none">
        <span
          className={cn(
            "font-display text-lg font-semibold tracking-[-0.01em]",
            tone === "light" ? "text-surface" : "text-ink",
          )}
        >
          {site.name}
        </span>
        <span
          className={cn(
            "label-caps mt-1 text-[0.5625rem]",
            tone === "light" ? "text-accent-glow/80" : "text-accent-ink",
          )}
        >
          Ayurveda · Kerala
        </span>
      </span>
    </Link>
  );
}
